[project]
name = "fishhoof"
version = "0.0.2"
description = "Add your description here"
authors = [
    { name = "Taylor Monacelli", email = "taylormonacelli@gmail.com" }
]
dependencies = [
    "jinja2>=3.1.3",
    "humanize>=4.9.0",
    "pytimeparse>=1.1.8",
]
readme = "README.md"
requires-python = ">= 3.8"

[project.scripts]
fishhoof = "fishhoof:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.rye]
managed = true
dev-dependencies = [
    "black>=24.2.0",
]

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build.targets.wheel]
packages = ["src/fishhoof"]

[tool.ruff.lint]
extend-select = ["I"]
