[project]
name = "ph-utils"
version = "0.0.10"
description = "The python3 tool classes"
authors = [
    { name = "Tenny", email = "tenny.shu@foxmail.com" },
]
dependencies = []
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3.10",
    "License :: OSI Approved :: Mulan Permissive Software License v2 (MulanPSL-2.0)",
    "Operating System :: OS Independent",
]

[project.license]
text = "MulanPSL-2.0"

[project.urls]
Homepage = "https://gitee.com/towardly/ph-utils_py"
"Bug Tracker" = "https://gitee.com/towardly/ph-utils_py/issues"

[tool.rye]
managed = true
dev-dependencies = []

[tool.hatch.metadata]
allow-direct-references = true

[tool.pdm]
distribution = true

[build-system]
requires = [
    "pdm-backend",
]
build-backend = "pdm.backend"
