[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
[project]
name = "EasyDrive"
version = "0.0.2"
authors = [
  { name="RanchMonster", email="ranchmonster06@outlook.com" },
]
description = "EasyGoogle Drive access"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]