[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "pyfancytranslator"
version = "1.1.1"
authors = [
    { name = "Ashenguard", email = "ashenguard@agmstudio.xyz" },
]
description = "A well built translator with placeholders"
readme = "README.md"
requires-python = ">=3.12"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Development Status :: 5 - Production/Stable",
    "Operating System :: OS Independent",
]
dependencies = []

[project.urls]
"Homepage" = "https://github.com/agm-studio/fancytranslator"
"Bug Tracker" = "https://github.com/agm-studio/fancytranslator/issues"