[tool.poetry]
name = "nonebot-plugin-plus-one"
version = "0.1.2"
description = "全新复读姬，支持文本、图片表情复读。任意群聊触发 +1，姬就 +1。轻巧、专注，不使用任何数据库，不使用任何文件存储"
authors = ["yejue <1145331931@qq.com>"]
readme = "README.md"
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
nonebot2 = "^2.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.urls]
homepage = "https://github.com/yejue/nonebot-plugin-plus-one"
repository = "https://github.com/yejue/nonebot-plugin-plus-one"
