[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
[project]
name = "proxypool_util"
version = "0.1.4"
authors = [
  { name="Mykhailo Razbeiko", email="mykhailo.razb@gmail.com" },
]
description = "Proxy pool to rotate and manage proxies"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://github.com/MykhailoRp/proxypool_util"
Issues = "https://github.com/MykhailoRp/proxypool_util/issues"