[tool.poetry]
name = "etypes"
version = "1.0.0"
description = "A python module to store, encrypt and decrypt type hinted strings in a python file"
authors = ["Dan Brosnan <dpjbrosnan@gmail.com>"]
packages = [{ include = "etypes", from = "src" }]


[tool.poetry.dependencies]
python = "^3.10"
click = "^8.0"



[tool.poetry.group.test.dependencies]
pytest = "^8.2.1"


[tool.poetry.group.development.dependencies]
pdbpp = "^0.10.3"
black = "^24.4.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"


[tool.poetry.scripts]
etypes = "etypes.cli.etypes:main"

[tool.poetry.extras]
ansible = ["ansible"]