[build-system]
requires = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "techtribe-addressbook"
version = "1.0.3"
description = "Save your data easy and convenient"
readme = "README.md"
license = { file = "LICENSE" }
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
keywords = ["addressbook", "techtribe"]
dependencies = [
    "prompt-toolkit==3.0.43",
    "wcwidth==0.2.13",
]
[project.urls]
Homepage = "https://github.com/Oldestgraf/TechTribe"

[project.scripts]
realpython = "TechTribe.__main__:main"