[build-system]
requires = [
    "setuptools>=42",
    "wheel"
]
build-backend = "setuptools.build_meta"

[project]
name = "ansar-connect"
readme = "README.md"
authors = [
  { name="Scott Woods", email="scott.18.ansar@gmail.com.com" }
]
requires-python = ">=3.7"
classifiers=[
	"Development Status :: 4 - Beta",
	"Intended Audience :: Developers",
	"Programming Language :: Python :: 3",
	"License :: OSI Approved :: MIT License",
	"Operating System :: OS Independent",
	"Topic :: Software Development :: Libraries"
]
dynamic = ["description", "version", "scripts"]
dependencies = [
    "cffi>=1.16.0",
    "PyNaCl>=1.5.0",
    "ansar-create>=0.1.98"
]

[project.urls]
Documentation = "https://ansar-connect-manual.s3.ap-southeast-2.amazonaws.com/0.1.1/index.html"
