[tool.poetry]
name = "resource_abstractor_client"
version = "0.1.3"
description = "TODO"
authors = ["Mahmoud Elkodary"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
requests = "^2.27.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
