[build-system]
requires = [
    "pdm-backend",
]
build-backend = "pdm.backend"

[project]
name = "kgr"
version = "0.3.0"
dependencies = [
    "requests",
    "geopy",
    "bs4",
]
authors = [
    { name = "Dmitry Luschan", email = "dluschan@gmail.com" },
]
maintainers = [
    { name = "Dmitry Luschan", email = "dluschan@gmail.com" },
]
description = "Miltitool for convert data from https://memopzk.org to Google Maps"
readme = "README.md"
keywords = []
classifiers = [
    "Development Status :: 4 - Beta",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
    "Topic :: Utilities",
    "Environment :: Console",
]

[project.license]
file = "LICENSE"

[project.urls]
Homepage = "https://github.com/dluschan/kgr"
Repository = "https://github.com/dluschan/kgr.git"
Issues = "https://github.com/dluschan/kgr/issues"

[tool]
