[tool.poetry]
package-mode = true
name = "suskabot"
version = "0.2.4"
description = "telegram bot with various functions"
authors = ["vinyl_summer <vinyl6428@gmail.dotcom>"]
readme = "README.md"
license = "LICENSE"

[[tool.poetry.source]]
name = "gitlab"
url = "https://gitlab.com/api/v4/projects/45324644/packages/pypi/simple"
priority = "primary"

[tool.poetry.dependencies]
python = "^3.11"
lingua-language-detector = "^2.0.2"
translators = "^5.9.1"
pytube = { source = "gitlab", version = "15.0.2" }
python-telegram-bot = {extras = ["job-queue"], version = "^21.1.1"}
pydantic = "^2.7.1"
python-dotenv = "^1.0.1"

[tool.poetry.group.dev.dependencies]
pytest = "^7.4"
pytest-sugar = "*"
ruff = "^0.4.2"
pytest-xdist = "^3.6.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
