[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "kossou-hillshade-cli"
version = "0.0.4" # Don't forget to match with version.py and docs/source/conf.py
authors = [
  { name="Anthony Aylward", email="anthony.aylward@protonmail.com" },
]
description = "Plot hillshade over Lake Kossou using satellite elevation data"
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
    "License :: OSI Approved :: BSD License",
]
dependencies = [
    "kossou-hillshade-base",
    "misaka"
]

[project.urls]
"Homepage" = "https://https://gitlab.com/aaylward/kossou-hillshade-cli"
"Documentation" = "https://aaylward.gitlab.io/kossou-hillshade-cli"

[project.scripts]
kossou-hillshade = "kossou_hillshade_cli.kossou_hillshade_cli:main"
